apiVersion: apps/v1
kind: Deployment
metadata:
  name: miracle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-apt
  template:
    metadata:
      labels:
        app: my-apt
    spec:
      containers:
        - name: miracleapp
          image: ajyke/miracle
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: miraclesvc
spec:
  type: LoadBalancer
  selector:
    app: my-apt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31500
